### ISSUE TITLE
Deltoids is listed twice

### ISSUE THREAD

**Issue by mphill** [HichamELBSI/react-native-body-highlighter#45]
https://github.com/HichamELBSI/react-native-body-highlighter/blob/e4923f2e87340d01d0054cc36629e7266682d6b9/index.tsx#L16

It was previously "front-deltoids" and "back-deltoids"

**Comment by HichamELBSI** [comment]
Thanks for your feedback @mphill , since the Body component now renders only on one side at a time, it's no longer necessary to specify front or back. If the selected body part is present on both sides, it will be highlighted (just like the head, hands, feet, forearms, ankles, etc.). Concerning the deltoids, I think we should use `shoulders` and not `deltoids`. That seems more appropriate. I'll take the time to work on it soon, thanks again.

**Comment by mphill** [comment]
I agree. Replace front / back deltoids with shoulders.
